name: slowfast
channels:
  - conda-forge
dependencies:
  - av=9.1.0
  - cudatoolkit=11.1.1
  - detectron2=0.6
  - fairscale=0.4.3
  - fvcore=0.1.5.post20221122
  - iopath=0.1.9
  - moviepy=1.0.3
  - pip=21.0.1
  - pandas=1.5.2
  - psutil=5.9.4
  - py-opencv=4.5.2
  - python=3.8.8
  - pytorch-gpu=1.8.0
  - scikit-learn=1.2.0
  - scipy=1.9.3
  - simplejson=3.18.0
  - tensorboard=2.11.0
  - torchvision=0.9.0
  - pip:
    - git+https://github.com/facebookresearch/pytorchvideo.git@702f9f42569598c5cce8c5e2dd7e37c3d6c46efd#egg=pytorchvideo
